//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZKARAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class arzyaabi
    {
        public int id { get; set; }
        public int taskhkilid { get; set; }
        public string roobarzyaabi { get; set; }
        public string irteqaamozeshwaelaanbast { get; set; }
        public string arzaabishoda { get; set; }
        public string noomraarzyaabi { get; set; }
        public string tarikharzyaabi { get; set; }
        public string molahezaat { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
    
        public virtual taskhil taskhil { get; set; }
    }
}
